version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:stretch
    working_directory: /go/src/github.com/qlik-oss/kustomize
    steps:
      - checkout
      - run:
          name: "Verify build"
          command: |
            cd kustomize
            now=`date +"%T"`
            go build -o /tmp/kustomize-${now} main.go
  build_release:
    docker:
      - image: circleci/golang:stretch
    working_directory: /go/src/github.com/qlik-oss/kustomize
    steps:
      - checkout
      - run: make qlik-build-all
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            echo "--AB: CIRCLE_PROJECT_USERNAME: ${CIRCLE_PROJECT_USERNAME}"
            echo "--AB: CIRCLE_PROJECT_REPONAME: ${CIRCLE_PROJECT_REPONAME}"
            echo "--AB: CIRCLE_SHA1: ${CIRCLE_SHA1}"
            echo "--AB: CIRCLE_TAG: ${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -prerelease ${CIRCLE_TAG} /go/src/github.com/qlik-oss/kustomize/bin
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build_release:
    jobs:
      - build_release:
          filters:
            tags:
              only: /^v.*/
